### ISSUE TITLE
Feature Request: Crafting Messages

### ISSUE THREAD

**Issue by starafar** [reiichi001/Dalamud.DiscordBridge#15]
Unless I've missed it, I can't find a message type to bring crafting messages into Discord via the bridge. Is this something that can be added?

**Comment by reiichi001** [comment]
I've released an updated version of DiscordBridge (1.2.6.0) that now ignores chat type sender masks (normalizes related chat types back into a single number, instead of a bunch of specialized ones).

If it's not being captured currently, you can use the ChatTyper plugin to determine which chat types are being used for it, and I can add a custom definition in. (The default chat typer settings should provide all the info I'd want, but you can turn on verbose mode for more detail, and that's fine too).
